import type {
  Category,
  HomepageContent,
  SiteSettings,
  Testimonial,
  TemplateWithCategory,
} from "@/lib/types";

/**
 * Catálogo de ejemplo.
 *
 * Cumple dos funciones:
 *  1. Es la fuente de `supabase/seed.sql` (mismos ids y slugs).
 *  2. Alimenta la vitrine cuando todavía no hay Supabase configurado,
 *     para poder ver y revisar el sitio antes de crear las cuentas.
 *
 * Una categoría por oficio. Dentro de cada una conviven varias plantillas
 * de distinto nivel y distinto precio: por ejemplo, en "Restaurantes" está
 * la Premium completa y, más adelante, versiones más sencillas y más
 * baratas. La categoría agrupa; la plantilla es lo que se compra.
 */

const CAT = "11111111-1111-4111-8111-0000000000";

/** Las categorías del catálogo, en el orden de la referencia de marca. */
export const seedCategories: Category[] = [
  { id: `${CAT}01`, name: "Clínica Dental", slug: "clinica-dental", icon: "🦷" },
  { id: `${CAT}02`, name: "Clínica Veterinaria", slug: "clinica-veterinaria", icon: "🐾" },
  { id: `${CAT}03`, name: "Pet Shop", slug: "pet-shop", icon: "🐕" },
  { id: `${CAT}04`, name: "Agencia Inmobiliaria", slug: "inmobiliaria", icon: "🏡" },
  { id: `${CAT}05`, name: "Agencia de Viajes", slug: "agencia-viajes", icon: "✈️" },
  { id: `${CAT}06`, name: "Hotel", slug: "hotel", icon: "🏨" },
  { id: `${CAT}07`, name: "Restaurantes", slug: "restaurante", icon: "🍽️" },
  { id: `${CAT}08`, name: "Panadería", slug: "panaderia", icon: "🥖" },
  { id: `${CAT}09`, name: "Boutique de Moda", slug: "boutique-moda", icon: "👗" },
  { id: `${CAT}10`, name: "Muebles y Decoración", slug: "muebles-decoracion", icon: "🛋️" },
  { id: `${CAT}11`, name: "Taller Mecánico", slug: "taller-mecanico", icon: "🔧" },
  { id: `${CAT}12`, name: "Piezas Automotrices", slug: "piezas-auto", icon: "⚙️" },
  { id: `${CAT}13`, name: "Taller de Motos", slug: "taller-motos", icon: "🏍️" },
  { id: `${CAT}14`, name: "Piezas para Moto", slug: "piezas-moto", icon: "🔩" },
  { id: `${CAT}15`, name: "Pizzería", slug: "pizzeria", icon: "🍕" },
  { id: `${CAT}16`, name: "Materiales de Construcción", slug: "materiales-construccion", icon: "🧱" },
  { id: `${CAT}17`, name: "Obras y Construcción", slug: "obras-construccion", icon: "🏗️" },
  { id: `${CAT}18`, name: "Pesca", slug: "pesca", icon: "🎣" },
  { id: `${CAT}21`, name: "Energía Solar", slug: "energia-solar", icon: "☀️" },
  { id: `${CAT}22`, name: "Mudanzas y Transportes", slug: "mudanzas-transportes", icon: "🚚" },
  { id: `${CAT}23`, name: "Electrónica", slug: "electronica", icon: "📱" },
  { id: `${CAT}24`, name: "Hamburguesería", slug: "hamburgueseria", icon: "🍔" },
  { id: `${CAT}25`, name: "Alquiler de Coches", slug: "alquiler-coches", icon: "🚗" },
  { id: `${CAT}26`, name: "Concesionaria de Automóviles", slug: "concesionaria", icon: "🚘" },
  { id: `${CAT}27`, name: "Instrumentos Musicales", slug: "instrumentos-musicales", icon: "🎸" },
  { id: `${CAT}28`, name: "Perfumería", slug: "perfumeria", icon: "🧴" },
  { id: `${CAT}29`, name: "Relojería", slug: "relojeria", icon: "⌚" },
  { id: `${CAT}30`, name: "Frutería y Verdulería", slug: "fruteria", icon: "🥬" },
  { id: `${CAT}31`, name: "Abogados y Consultoría Legal", slug: "abogados", icon: "⚖️" },
  // Categorías "paraguas" del marketplace general (agrupan varios rubros de arriba).
  { id: `${CAT}32`, name: "Negocios", slug: "negocios", icon: "💼" },
  { id: `${CAT}33`, name: "Tienda Online", slug: "tienda-online", icon: "🛒" },
  { id: `${CAT}34`, name: "Salud y Belleza", slug: "salud-belleza", icon: "💆" },
  { id: `${CAT}35`, name: "Portafolios", slug: "portafolios", icon: "🖼️" },
  { id: `${CAT}36`, name: "Blogs y Revistas", slug: "blogs-revistas", icon: "📰" },
  { id: `${CAT}37`, name: "Servicios Profesionales", slug: "servicios-profesionales", icon: "🤝" },
  { id: `${CAT}38`, name: "Sistemas PDV", slug: "pdv", icon: "🖥️" },
  { id: `${CAT}39`, name: "Combos (Web + PDV)", slug: "combos", icon: "📦" },
];

const byslug = (slug: string) => seedCategories.find((c) => c.slug === slug)!;

interface SeedTemplate {
  id: string;
  categorySlug: string;
  title: string;
  slug: string;
  short_description: string;
  full_description: string;
  price_cents: number;
  preview_url: string | null;
  /** Degradado de respaldo si algún día falta la miniatura. */
  gradient: string;
  features: string[];
  /** Rubro dentro de /pdvs (además de "pdv" en sí); vacío para el resto del catálogo. */
  tags?: string[];
  /** Solo para combos: la miniatura es la del producto incluido, no la del propio slug. */
  thumbnailSlug?: string;
}

const TPL = "22222222-2222-4222-8222-0000000000";

const RESPONSIVE = "Responsive (móvil, tablet y desktop)";
const SEO = "Optimizado para Google (SEO)";

/**
 * Catálogo en construcción: cada plantilla se añade cuando llega su
 * paquete (imagen de referencia + prompt) y su demo está terminada.
 */
const seed: SeedTemplate[] = [
  {
    id: `${TPL}01`,
    categorySlug: "clinica-dental",
    title: "Clínica Dental Premium",
    slug: "clinica-dental-premium",
    short_description: "Clínica dental completa: tratamientos, equipo, urgencias y cita previa online.",
    full_description:
      "Para clínicas dentales y consultas privadas: catálogo de 6 tratamientos con ficha propia, equipo de especialistas, franja de urgencias 24h, promoción de bienvenida, preguntas frecuentes y formulario de cita previa. Paleta blanco + azul que transmite confianza, higiene y tecnología.",
    price_cents: 19900,
    preview_url: "/demos/clinica-dental-premium/index.html",
    gradient: "linear-gradient(160deg,#0a1e3d,#1d5fb8 55%,#081428)",
    features: [
      "Cita previa online con formulario validado",
      "6 tratamientos con ficha propia",
      "Equipo de especialistas",
      "Urgencias 24h y financiación",
      "Preguntas frecuentes (acordeón)",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}02`,
    categorySlug: "agencia-viajes",
    title: "Agencia de Viajes Premium",
    slug: "agencia-viajes-premium",
    short_description: "Agencia de viajes con buscador, destinos, paquetes y planificación a medida.",
    full_description:
      "Para agencias de viajes y turoperadores: buscador de viajes, carrusel de destinos destacados con precios y valoraciones, tarjetas de cruceros y ofertas, 8 tipos de viaje filtrables, paquetes preparados, testimonios, preguntas frecuentes, blog y formulario de propuesta a medida con validación. Paleta verde azulado + coral, tipografía Playfair Display.",
    price_cents: 21900,
    preview_url: "/demos/agencia-viajes-premium/index.html",
    gradient: "linear-gradient(160deg,#0b3b3c,#1a5f60 55%,#08292a)",
    features: [
      "Buscador de viajes funcional",
      "Carrusel de destinos con valoraciones",
      "8 tipos de viaje filtrables",
      "Paquetes y ofertas destacadas",
      "Formulario de propuesta con validación",
      "Preguntas frecuentes y blog",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}03`,
    categorySlug: "abogados",
    title: "Consultoría Legal & Empresarial Premium",
    slug: "consultoria-legal-premium",
    short_description:
      "Despacho de abogados con 10 áreas de especialización, blog jurídico y formulario de consulta.",
    full_description:
      "Para despachos de abogados y consultoras: las 10 áreas más demandadas del derecho con ficha propia (empresarial, laboral, familia, inmobiliario, civil, penal, fiscal, comercial, propiedad intelectual y consultoría), foto de portada y de equipo, proceso de trabajo en cuatro pasos, opiniones de clientes, blog jurídico, preguntas frecuentes y formulario de consulta con validación. Paleta azul noche + oro, tipografía Playfair Display. Si no subes foto, la portada dibuja una balanza dorada y las áreas llevan iconos en vectores, así que se ve nítido desde el primer minuto.",
    price_cents: 24900,
    preview_url: "/demos/consultoria-legal-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "10 áreas de especialización con icono propio",
      "Formulario de consulta con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog jurídico y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      "Foto de portada y de equipo incluidas",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}04`,
    categorySlug: "restaurante",
    title: "Restaurante Premium",
    slug: "restaurante-premium",
    short_description:
      "Restaurante de cocina de autor: carta con precios, reservas, galería y blog.",
    full_description:
      "Para restaurantes de cocina de autor y locales con carta de vinos: portada con carrusel de fotos, buscador de disponibilidad, seis secciones con foto propia, carta completa agrupada en entrantes, principales y postres con sus precios, cifras del local, opiniones que van rotando solas, galería, blog y formulario de reserva con validación (email, teléfono y fechas pasadas). Paleta negro + terracota + oro, tipografía Playfair Display. El dueño cambia la carta entera desde el panel escribiendo una línea por plato.",
    price_cents: 24900,
    preview_url: "/demos/restaurante-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#2a2118 55%,#0d0d10)",
    features: [
      "Carta completa con precios, editable línea a línea",
      "Portada con carrusel de hasta 4 fotos",
      "Buscador de disponibilidad y formulario de reserva",
      "Galería de 8 fotos y blog",
      "Opiniones de clientes que rotan solas",
      "Botón de WhatsApp para reservas",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}05`,
    categorySlug: "panaderia",
    title: "Panadería con Pedidos Online",
    slug: "panaderia-premium",
    short_description:
      "Panadería con catálogo de productos, cesta y pedidos que llegan por WhatsApp.",
    full_description:
      "Para panaderías, pastelerías y cafeterías que quieren vender sin depender de las plataformas de reparto: catálogo de productos por categorías con filtros, cesta de la compra que recuerda lo que has elegido aunque cierres la página, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio, con productos, cantidades, totales, dirección y hora. Sin comisiones por pedido y sin pasarela de pago que configurar. Paleta crema + ámbar, tipografía Playfair Display.",
    price_cents: 19900,
    preview_url: "/demos/panaderia-premium/index.html",
    gradient: "linear-gradient(160deg,#f8f1e6,#e8a33d 55%,#c9821f)",
    features: [
      "Catálogo de productos con filtros por categoría",
      "Cesta de la compra que no se pierde al cerrar",
      "Recogida en tienda o entrega, con pedido mínimo",
      "El pedido llega entero por WhatsApp",
      "Sin comisiones y sin pasarela que configurar",
      "Horarios, historia del negocio y contacto",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}06`,
    categorySlug: "clinica-veterinaria",
    title: "Clínica Veterinaria Premium",
    slug: "veterinaria-premium",
    short_description:
      "Clínica veterinaria con urgencias 24h, planes de salud mensuales y cita online.",
    full_description:
      "Para clínicas veterinarias y centros de salud animal: ocho servicios con ficha propia, franja de urgencias 24 horas con llamada directa, tres planes de salud por cuota mensual (cachorro, adulto y sénior) con el plan destacado resaltado en color, equipo con foto y su especialidad, formulario de cita que pregunta qué animal es y valida teléfono, correo y fechas pasadas, opiniones y preguntas frecuentes. Paleta verde + melocotón, tipografía Playfair Display. Si no subes foto de portada o de algún miembro del equipo, se dibujan automáticamente (un perro y un gato ilustrados, o las iniciales en un círculo), así que se ve nítido desde el primer minuto.",
    price_cents: 22900,
    preview_url: "/demos/veterinaria-premium/index.html",
    gradient: "linear-gradient(160deg,#e3f2ee,#12786a 55%,#0b5a4f)",
    features: [
      "Tres planes de salud por cuota mensual",
      "Franja de urgencias 24h con llamada directa",
      "8 servicios con icono propio",
      "Cita online que pregunta qué animal es",
      "Equipo con foto y especialidad de cada uno",
      "Equipo, opiniones y preguntas frecuentes",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}07`,
    categorySlug: "pet-shop",
    title: "Pet Shop Premium",
    slug: "pet-shop-premium",
    short_description:
      "Tienda de mascotas con catálogo, carrito, favoritos y servicios de peluquería y hotel.",
    full_description:
      "Para tiendas de animales y centros de estética canina: catálogo de productos con etiquetas de oferta y novedad, valoraciones con estrellas, carrito de la compra con favoritos que recuerda lo elegido, ocho categorías filtrables (perros, gatos, pequeños animales...), franja de servicios (baño y peluquería, hotel, guardería, adiestramiento) y pedido que se envía por WhatsApp. Paleta azul petróleo + terracota, tipografía Inter.",
    price_cents: 21900,
    preview_url: "/demos/pet-shop-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#3b7a9c 55%,#0a3650)",
    features: [
      "Catálogo con ofertas, novedades y valoraciones",
      "Carrito de la compra con favoritos",
      "8 categorías filtrables",
      "Servicios de peluquería, hotel y guardería",
      "El pedido llega por WhatsApp",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}08`,
    categorySlug: "fruteria",
    title: "Frutería y Verdulería Premium",
    slug: "fruteria-premium",
    short_description: "Frutería online con catálogo de productos frescos, ofertas y carrito de compra.",
    full_description:
      "Para fruterías, verdulerías y tiendas de productos ecológicos: catálogo con ofertas y novedades, ocho categorías filtrables (frutas, verduras, frutos secos, ecológicos...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta verde + terracota, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios, así que carga al instante.",
    price_cents: 19900,
    preview_url: "/demos/fruteria-premium/index.html",
    gradient: "linear-gradient(160deg,#1f5c3a,#4a9d7f 55%,#123b26)",
    features: [
      "Catálogo con ofertas y novedades",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}09`,
    categorySlug: "relojeria",
    title: "Relojería Premium",
    slug: "relojeria-premium",
    short_description: "Relojería online con catálogo de marcas, valoraciones y carrito de compra.",
    full_description:
      "Para relojerías y joyerías: catálogo de relojes con etiquetas de oferta y novedad, valoraciones con estrellas, ocho categorías filtrables (hombre, mujer, smartwatch, joyería...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul noche + dorado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/relojeria-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#e0b64a 55%,#0a3650)",
    features: [
      "Catálogo con ofertas, novedades y valoraciones",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}10`,
    categorySlug: "piezas-auto",
    title: "Piezas Automotrices Premium",
    slug: "piezas-auto-premium",
    short_description: "Tienda de piezas de automóvil con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de recambios y piezas de automóvil: catálogo con descuentos destacados, ocho categorías filtrables (frenos, motor, suspensión, electricidad...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta roja + gris oscuro, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/piezas-auto-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#c0392b 55%,#0d0d10)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}11`,
    categorySlug: "piezas-moto",
    title: "Piezas para Moto Premium",
    slug: "piezas-moto-premium",
    short_description: "Tienda de recambios de moto con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de recambios de motocicleta: catálogo con descuentos destacados, ocho categorías filtrables (frenos, motor, escapes, equipación...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta roja + gris oscuro, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 19900,
    preview_url: "/demos/piezas-moto-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#e2694a 55%,#0d0d10)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}12`,
    categorySlug: "muebles-decoracion",
    title: "Muebles y Decoración Premium",
    slug: "muebles-decoracion-premium",
    short_description: "Tienda de muebles y decoración con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de muebles y decoración del hogar: catálogo con descuentos destacados, ocho categorías filtrables (salón, dormitorio, iluminación, textiles...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta terracota + crema, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/muebles-decoracion-premium/index.html",
    gradient: "linear-gradient(160deg,#8a6bb0,#e2694a 55%,#5a4478)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}13`,
    categorySlug: "perfumeria",
    title: "Perfumería Premium",
    slug: "perfumeria-premium",
    short_description: "Perfumería online con catálogo de fragancias, ofertas y carrito de compra.",
    full_description:
      "Para perfumerías y tiendas de cosmética: catálogo con descuentos destacados, ocho categorías filtrables (mujer, hombre, unisex, cosmética...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta morada + rosa, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 19900,
    preview_url: "/demos/perfumeria-premium/index.html",
    gradient: "linear-gradient(160deg,#8a6bb0,#d97ba0 55%,#5a4478)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}14`,
    categorySlug: "pesca",
    title: "Pesca Premium",
    slug: "pesca-premium",
    short_description: "Tienda de artículos de pesca con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de artículos de pesca: catálogo con descuentos destacados, ocho categorías filtrables (cañas, carretes, señuelos, ropa...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + verde, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 19900,
    preview_url: "/demos/pesca-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#4a9d7f 55%,#0a3650)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}15`,
    categorySlug: "energia-solar",
    title: "Energía Solar Premium",
    slug: "energia-solar-premium",
    short_description: "Tienda de energía solar con catálogo de productos y solicitud de presupuesto.",
    full_description:
      "Para instaladoras y tiendas de energía solar: catálogo de placas, inversores, baterías y kits solares, ocho categorías filtrables, carrito de la compra con favoritos y pedido o solicitud de presupuesto que se envía por WhatsApp. Paleta azul noche + amarillo solar, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 22900,
    preview_url: "/demos/energia-solar-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#e0a838 55%,#0a3650)",
    features: [
      "Catálogo con 8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido o presupuesto llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      "Pensado para instaladoras y tiendas técnicas",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}16`,
    categorySlug: "taller-mecanico",
    title: "Taller Mecánico Premium",
    slug: "taller-mecanico-premium",
    short_description: "Taller mecánico con cita online, 10 servicios y formulario de presupuesto.",
    full_description:
      "Para talleres mecánicos y centros de diagnóstico: diez áreas de servicio con icono propio (diagnóstico electrónico, frenos, neumáticos, ITV...), foto de portada y de equipo, proceso de trabajo en cuatro pasos, cifras del taller, opiniones de clientes, blog y formulario de cita con validación. Tipografía Playfair Display. Los colores de marca (acento y fondo oscuro) se cambian con un selector desde el propio panel, sin tocar código: todo el sitio se actualiza al instante.",
    price_cents: 22900,
    preview_url: "/demos/taller-mecanico-premium/index.html",
    gradient: "linear-gradient(160deg,#170f0f,#2b1717 55%,#170f0f)",
    features: [
      "10 áreas de servicio con icono propio",
      "Color de marca editable desde el panel",
      "Formulario de cita con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}17`,
    categorySlug: "taller-motos",
    title: "Taller de Motos Premium",
    slug: "taller-motos-premium",
    short_description: "Taller de motos con cita online, 10 servicios y formulario de presupuesto.",
    full_description:
      "Para talleres especializados en motocicletas: diez áreas de servicio con icono propio (mantenimiento, frenos, cadena y transmisión, motor, restauración de clásicas...), foto de portada y de equipo, proceso de trabajo en cuatro pasos, cifras del taller, opiniones de clientes, blog y formulario de cita con validación. Tipografía Playfair Display. Los colores de marca (acento y fondo oscuro) se cambian con un selector desde el propio panel, sin tocar código: todo el sitio se actualiza al instante.",
    price_cents: 22900,
    preview_url: "/demos/taller-motos-premium/index.html",
    gradient: "linear-gradient(160deg,#141414,#3e3e3e 55%,#141414)",
    features: [
      "10 áreas de servicio con icono propio",
      "Color de marca editable desde el panel",
      "Formulario de cita con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}18`,
    categorySlug: "mudanzas-transportes",
    title: "Mudanzas y Transportes Premium",
    slug: "mudanzas-transportes-premium",
    short_description: "Empresa de mudanzas con 10 servicios y formulario de solicitud de presupuesto.",
    full_description:
      "Para empresas de mudanzas y transporte: diez áreas de servicio con ficha propia (mudanzas particulares, internacionales, guarda-muebles...), proceso de trabajo en cuatro pasos, cifras de la empresa, opiniones de clientes, blog y formulario de presupuesto con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.",
    price_cents: 22900,
    preview_url: "/demos/mudanzas-transportes-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "10 áreas de servicio con icono propio",
      "Formulario de presupuesto con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      "Sin fotos: todo en vectores, carga al instante",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}19`,
    categorySlug: "obras-construccion",
    title: "Obras y Construcción Premium",
    slug: "obras-construccion-premium",
    short_description: "Empresa de construcción con 10 servicios y formulario de solicitud de presupuesto.",
    full_description:
      "Para empresas de obras y construcción: diez áreas de servicio con ficha propia (reformas integrales, obra nueva, rehabilitación...), proceso de trabajo en cuatro pasos, cifras de la empresa, opiniones de clientes, blog y formulario de presupuesto con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.",
    price_cents: 24900,
    preview_url: "/demos/obras-construccion-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "10 áreas de servicio con icono propio",
      "Formulario de presupuesto con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      "Sin fotos: todo en vectores, carga al instante",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}20`,
    categorySlug: "pizzeria",
    title: "Pizzería Premium",
    slug: "pizzeria-premium",
    short_description: "Pizzería con pedidos online, cesta de la compra y entrega o recogida en tienda.",
    full_description:
      "Para pizzerías y restaurantes italianos que quieren vender sin depender de las plataformas de reparto: catálogo de pizzas por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + rojo italiano, tipografía Playfair Display.",
    price_cents: 19900,
    preview_url: "/demos/pizzeria-premium/index.html",
    gradient: "linear-gradient(160deg,#1a1210,#c0392b 55%,#0d0d0d)",
    features: [
      "Catálogo de pizzas con filtros por categoría",
      "Cesta de la compra que no se pierde al cerrar",
      "Recogida en tienda o entrega, con pedido mínimo",
      "El pedido llega entero por WhatsApp",
      "Sin comisiones y sin pasarela que configurar",
      "Horarios, historia del negocio y contacto",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}21`,
    categorySlug: "boutique-moda",
    title: "Boutique de Moda Premium",
    slug: "boutique-moda-premium",
    short_description: "Boutique de moda online con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para boutiques de moda y tiendas de ropa: catálogo con descuentos destacados, ocho categorías filtrables (mujer, hombre, calzado, accesorios...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta rosa + terracota, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 19900,
    preview_url: "/demos/boutique-moda-premium/index.html",
    gradient: "linear-gradient(160deg,#8a6bb0,#d97ba0 55%,#5a4478)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}22`,
    categorySlug: "electronica",
    title: "Electrónica Premium",
    slug: "electronica-premium",
    short_description: "Tienda de electrónica con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de electrónica y tecnología: catálogo con descuentos destacados, ocho categorías filtrables (móviles, portátiles, audio, gaming...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + morado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/electronica-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#8a6bb0 55%,#0a3650)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}23`,
    categorySlug: "materiales-construccion",
    title: "Materiales de Construcción Premium",
    slug: "materiales-construccion-premium",
    short_description: "Almacén de materiales de construcción con catálogo y carrito de compra.",
    full_description:
      "Para almacenes de materiales de construcción y ferreterías: catálogo con ocho categorías filtrables (cemento, ladrillos, herramientas, maquinaria...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta terracota + amarillo, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/materiales-construccion-premium/index.html",
    gradient: "linear-gradient(160deg,#c9542f,#e0a838 55%,#8a3a1f)",
    features: [
      "Catálogo con 8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      "Pensado para almacenes y ferreterías",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}24`,
    categorySlug: "hamburgueseria",
    title: "Hamburguesería Premium",
    slug: "hamburgueseria-premium",
    short_description: "Hamburguesería con pedidos online, cesta de la compra y entrega o recogida en tienda.",
    full_description:
      "Para hamburgueserías y locales de comida rápida de calidad: catálogo de hamburguesas por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + terracota, tipografía Playfair Display.",
    price_cents: 19900,
    preview_url: "/demos/hamburgueseria-premium/index.html",
    gradient: "linear-gradient(160deg,#1a1210,#c9542f 55%,#0d0d0d)",
    features: [
      "Catálogo de hamburguesas con filtros por categoría",
      "Cesta de la compra que no se pierde al cerrar",
      "Recogida en tienda o entrega, con pedido mínimo",
      "El pedido llega entero por WhatsApp",
      "Sin comisiones y sin pasarela que configurar",
      "Horarios, historia del negocio y contacto",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}25`,
    categorySlug: "inmobiliaria",
    title: "Agencia Inmobiliaria Premium",
    slug: "inmobiliaria-premium",
    short_description: "Inmobiliaria con 10 servicios, valoración gratuita y formulario de contacto.",
    full_description:
      "Para agencias inmobiliarias: diez áreas de servicio con ficha propia (venta, alquiler, obra nueva, valoración, asesoría hipotecaria...), sección de propiedades destacadas con foto, precio y ficha técnica, proceso de trabajo en cuatro pasos, cifras de la agencia, opiniones de clientes, blog y formulario de contacto con validación. Paleta azul noche + dorado, tipografía Playfair Display.",
    price_cents: 22900,
    preview_url: "/demos/inmobiliaria-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "Propiedades destacadas con foto y ficha técnica",
      "10 áreas de servicio con icono propio",
      "Formulario de contacto con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}26`,
    categorySlug: "hotel",
    title: "Hotel Premium",
    slug: "hotel-premium",
    short_description: "Hotel con 10 servicios, reserva directa y formulario de contacto.",
    full_description:
      "Para hoteles y alojamientos: diez áreas de servicio con ficha propia (habitaciones, suites, restaurante, spa, eventos...), proceso de reserva en cuatro pasos, cifras del hotel, opiniones de huéspedes, blog y formulario de reserva con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.",
    price_cents: 22900,
    preview_url: "/demos/hotel-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "10 áreas de servicio con icono propio",
      "Formulario de reserva con validación",
      "Proceso de reserva en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Botones de WhatsApp, teléfono y email",
      "Sin fotos: todo en vectores, carga al instante",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}27`,
    categorySlug: "alquiler-coches",
    title: "Alquiler de Coches Premium",
    slug: "alquiler-coches-premium",
    short_description: "Alquiler de coches con flota propia, catálogo por categorías y reserva por WhatsApp.",
    full_description:
      "Para empresas de alquiler de coches con flota propia: catálogo de vehículos por categorías (económicos, SUV, eléctricos, lujo...), carrito de reserva con favoritos y solicitud que se envía por WhatsApp. Paleta negro + amarillo, tipografía Inter. No necesita fotos de vehículo: todo se muestra con iconos propios.",
    price_cents: 22900,
    preview_url: "/demos/alquiler-coches-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#e0a838 55%,#0d0d10)",
    features: [
      "Catálogo de vehículos por categorías",
      "Carrito de reserva con favoritos",
      "La solicitud llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      "Pensado para empresas con flota propia",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}28`,
    categorySlug: "concesionaria",
    title: "Concesionaria de Automóviles Premium",
    slug: "concesionaria-premium",
    short_description: "Concesionaria con vehículos nuevos y de ocasión, catálogo y solicitud por WhatsApp.",
    full_description:
      "Para concesionarias de automóviles: catálogo de vehículos nuevos y de ocasión por categorías, carrito de interés con favoritos y solicitud de información que se envía por WhatsApp. Paleta negro + amarillo, tipografía Inter. No necesita fotos de vehículo: todo se muestra con iconos propios.",
    price_cents: 22900,
    preview_url: "/demos/concesionaria-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#e0a838 55%,#0d0d10)",
    features: [
      "Catálogo de nuevos y de ocasión por categorías",
      "Carrito de interés con favoritos",
      "La solicitud llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      "Pensado para concesionarias con vehículos propios",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}29`,
    categorySlug: "instrumentos-musicales",
    title: "Tienda de Instrumentos Musicales Premium",
    slug: "instrumentos-musicales-premium",
    short_description: "Tienda de instrumentos musicales con catálogo, ofertas y carrito de compra.",
    full_description:
      "Para tiendas de instrumentos musicales y equipos de sonido: catálogo con descuentos destacados, ocho categorías filtrables (guitarras, baterías, teclados, micrófonos...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta negro + dorado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.",
    price_cents: 21900,
    preview_url: "/demos/instrumentos-musicales-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#e0b64a 55%,#0d0d10)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      "Sin fotos: todo ilustrado, carga al instante",
      "Newsletter y franja de confianza",
      RESPONSIVE,
      SEO,
    ],
  },
  // ---- Catálogo de demostración del marketplace general (categorías "paraguas") ----
  {
    id: `${TPL}30`,
    categorySlug: "negocios",
    title: "Concesionaria Plus",
    slug: "concesionaria-plus",
    short_description: "Concesionaria de coches con catálogo, financiación y solicitud por WhatsApp.",
    full_description:
      "Para concesionarias y comercializadoras de vehículos: catálogo de coches nuevos y de ocasión con buscador por categoría, marca, año y precio, franjas de financiación y seguro, tasación de vehículo y solicitud de información directa por WhatsApp. Paleta roja + negra, tipografía Inter.",
    price_cents: 5900,
    preview_url: "/demos/concesionaria-premium/index.html",
    gradient: "linear-gradient(160deg,#141418,#c81a1c 55%,#0d0d10)",
    features: [
      "Buscador de vehículos por categoría, marca y año",
      "Financiación, seguro y tasación",
      "Solicitud de información por WhatsApp",
      "Favoritos ('Mi garaje')",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}31`,
    categorySlug: "tienda-online",
    title: "TechStore",
    slug: "techstore",
    short_description: "Tienda online de electrónica con catálogo, carrito y pedido por WhatsApp.",
    full_description:
      "Para tiendas de electrónica y tecnología: catálogo de productos con descuentos destacados, ocho categorías filtrables (móviles, portátiles, audio, gaming...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + morado, tipografía Inter.",
    price_cents: 6900,
    preview_url: "/demos/electronica-premium/index.html",
    gradient: "linear-gradient(160deg,#0e4c6b,#8a6bb0 55%,#0a3650)",
    features: [
      "Catálogo con descuentos destacados",
      "8 categorías filtrables",
      "Carrito de la compra con favoritos",
      "El pedido llega por WhatsApp",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}32`,
    categorySlug: "restaurante",
    title: "Sabor Express",
    slug: "sabor-express",
    short_description: "Comida rápida con pedidos online, cesta de la compra y entrega o recogida en tienda.",
    full_description:
      "Para hamburgueserías y locales de comida rápida de calidad: catálogo por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + terracota, tipografía Playfair Display.",
    price_cents: 4900,
    preview_url: "/demos/hamburgueseria-premium/index.html",
    gradient: "linear-gradient(160deg,#1a1210,#c9542f 55%,#0d0d0d)",
    features: [
      "Catálogo con filtros por categoría",
      "Cesta de la compra que no se pierde al cerrar",
      "Recogida en tienda o entrega, con pedido mínimo",
      "El pedido llega entero por WhatsApp",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}33`,
    categorySlug: "servicios-profesionales",
    title: "Servicios Pro",
    slug: "servicios-pro",
    short_description: "Consultoría profesional con áreas de especialización, blog y formulario de consulta.",
    full_description:
      "Para despachos y consultoras de servicios profesionales: áreas de especialización con ficha propia, proceso de trabajo en cuatro pasos, opiniones de clientes, blog y formulario de consulta con validación. Paleta azul noche + oro, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.",
    price_cents: 6900,
    preview_url: "/demos/consultoria-legal-premium/index.html",
    gradient: "linear-gradient(160deg,#0b1424,#16243d 55%,#080e1a)",
    features: [
      "Áreas de especialización con icono propio",
      "Formulario de consulta con validación",
      "Proceso de trabajo en cuatro pasos",
      "Blog y preguntas frecuentes",
      "Sin fotos: todo en vectores, carga al instante",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}34`,
    categorySlug: "salud-belleza",
    title: "GreenNature",
    slug: "greennature-spa",
    short_description: "Spa de bienestar natural con tratamientos, membresías y reserva online.",
    full_description:
      "Para spas, centros de bienestar y estética natural: catálogo de tratamientos con precio y duración, franja de filosofía de marca con cifras, tres planes de membresía mensual, equipo de terapeutas, formulario de reserva con validación, opiniones y preguntas frecuentes. Paleta verde + terracota, tipografía Playfair Display.",
    price_cents: 5900,
    preview_url: "/demos/greennature-spa/index.html",
    gradient: "linear-gradient(160deg,#e8f2ea,#3f7d52 55%,#2c5b3b)",
    features: [
      "Catálogo de tratamientos con precio y duración",
      "Tres planes de membresía mensual",
      "Formulario de reserva con validación",
      "Equipo, opiniones y preguntas frecuentes",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}35`,
    categorySlug: "negocios",
    title: "Business Pro",
    slug: "business-pro",
    short_description: "Consultoría empresarial con servicios, casos de éxito y formulario de contacto.",
    full_description:
      "Para consultoras y agencias de negocio: seis servicios con ficha propia, proceso de trabajo en cuatro pasos, cifras de la empresa, casos de éxito con resultado destacado, equipo, testimonios y formulario de contacto con validación. Paleta verde azulado + lima, tipografía Sora + Inter.",
    price_cents: 6900,
    preview_url: "/demos/business-pro/index.html",
    gradient: "linear-gradient(160deg,#0a3a3d,#1c7c80 55%,#0f5257)",
    features: [
      "6 servicios con icono propio",
      "Casos de éxito con resultado destacado",
      "Formulario de contacto con validación",
      "Equipo, testimonios y cifras de la empresa",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}36`,
    categorySlug: "portafolios",
    title: "Portfolio Creative",
    slug: "portfolio-creative",
    short_description: "Portafolio creativo con proyectos filtrables, sobre mí y formulario de contacto.",
    full_description:
      "Para diseñadores, fotógrafos y freelancers creativos: portafolio de proyectos con filtro por categoría, sección sobre mí con habilidades, servicios ofrecidos, testimonios de clientes y formulario de contacto. Paleta negro + coral, tipografía Sora + Inter.",
    price_cents: 4900,
    preview_url: "/demos/portfolio-creative/index.html",
    gradient: "linear-gradient(160deg,#0d0d0f,#ff4d5e 55%,#18181c)",
    features: [
      "Portafolio de proyectos con filtro por categoría",
      "Sección sobre mí con habilidades",
      "Formulario de contacto con validación",
      "Testimonios de clientes",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}37`,
    categorySlug: "blogs-revistas",
    title: "Magazine Pro",
    slug: "magazine-pro",
    short_description: "Revista digital con artículo destacado, categorías y newsletter.",
    full_description:
      "Para revistas digitales y blogs editoriales: artículo destacado y secundarios en portada, últimos artículos con autor y tiempo de lectura, explorador por secciones y formulario de newsletter. Paleta negro + rojo, tipografía Playfair Display + Inter.",
    price_cents: 4900,
    preview_url: "/demos/magazine-pro/index.html",
    gradient: "linear-gradient(160deg,#111113,#d1362f 55%,#1c1c1f)",
    features: [
      "Artículo destacado y secundarios en portada",
      "Últimos artículos con autor y tiempo de lectura",
      "Explorador por secciones",
      "Formulario de newsletter",
      RESPONSIVE,
      SEO,
    ],
  },
  {
    id: `${TPL}38`,
    categorySlug: "pdv",
    title: "PDV Retail Pro",
    slug: "pdv-retail-pro",
    short_description: "Interfaz de punto de venta táctil: catálogo, carrito y cobro en pantalla.",
    full_description:
      "Sistema de punto de venta (PDV) pensado para tiendas, kioscos y minimarkets. Catálogo por categorías, búsqueda de productos, carrito editable con cantidades, cálculo automático de IVA y tres métodos de pago (efectivo, tarjeta y móvil). Interfaz lista para tablet o pantalla táctil en el mostrador.",
    price_cents: 8900,
    preview_url: "/demos/pdv-retail-pro/index.html",
    gradient: "linear-gradient(160deg,#14161b,#ff7a1a 55%,#14161b)",
    features: [
      "Catálogo por categorías",
      "Carrito con cantidades",
      "Cálculo automático de IVA",
      "3 métodos de pago",
      "Ticket de venta en pantalla",
      "Pensado para tablet táctil",
    ],
    tags: ["retail"],
  },
  {
    id: `${TPL}40`,
    categorySlug: "pdv",
    title: "PDV Concesionaria Pro",
    slug: "pdv-concesionaria-pro",
    short_description: "Órdenes de servicio de taller y venta de repuestos, con datos de cliente y vehículo.",
    full_description:
      "Sistema de punto de venta pensado para concesionarias y talleres mecánicos: ficha de cliente y de vehículo en la misma orden, pestañas de trabajos/servicios y repuestos con su propio total, historial del vehículo, resumen de mano de obra + repuestos + impuestos, forma de pago y estado de la orden (pendiente, en proceso, terminada, entregada).",
    price_cents: 9900,
    preview_url: "/demos/pdv-concesionaria-pro/index.html",
    gradient: "linear-gradient(160deg,#101522,#1e4fd6 55%,#101522)",
    features: [
      "Ficha de cliente y de vehículo",
      "Trabajos/servicios y repuestos por pestañas",
      "Historial del vehículo",
      "Resumen de mano de obra + repuestos + IVA",
      "Estado de la orden (pendiente a entregada)",
      "4 formas de pago",
    ],
    tags: ["concesionaria", "taller-mecanico"],
  },
  {
    id: `${TPL}39`,
    categorySlug: "combos",
    title: "Combo Restaurante: Web + PDV",
    slug: "combo-restaurante-pdv",
    short_description: "El sitio web de Sabor Express + el sistema PDV Retail Pro, en un solo pack con descuento.",
    full_description:
      "Combo pensado para restaurantes y locales de comida rápida: incluye el sitio web completo \"Sabor Express\" (menú digital, pedidos y reservas) junto con el sistema de punto de venta \"PDV Retail Pro\" para cobrar en el mostrador. Al comprar el combo se entregan las dos plantillas completas. Compradas por separado costarían 137,90 €; en combo, con descuento.",
    price_cents: 9900,
    preview_url: "/demos/hamburgueseria-premium/index.html",
    gradient: "linear-gradient(160deg,#14161b,#ff7a1a 55%,#14161b)",
    features: [
      "Incluye sitio web Sabor Express",
      "Incluye PDV Retail Pro",
      "Ahorra frente a la compra por separado",
      "Ideal para restaurantes y comida rápida",
      "Dos archivos de descarga, uno por cada parte",
    ],
    tags: [
      "combo", "restaurante", "demo:hamburgueseria-premium", "demo:pdv-retail-pro",
      "incluye:sabor-express", "incluye:pdv-retail-pro",
    ],
    thumbnailSlug: "sabor-express",
  },
  {
    id: `${TPL}41`,
    categorySlug: "combos",
    title: "Combo Concesionaria Premium",
    slug: "combo-concesionaria-pdv",
    short_description: "El sitio web Concesionaria Plus + el sistema PDV Concesionaria Pro, en un solo pack con descuento.",
    full_description:
      "Combo pensado para concesionarias y talleres mecánicos: incluye el sitio web completo \"Concesionaria Plus\" (catálogo de vehículos, financiación y solicitud por WhatsApp) junto con el sistema de punto de venta \"PDV Concesionaria Pro\" para gestionar órdenes de taller y venta de repuestos en el mostrador. Al comprar el combo se entregan las dos plantillas completas. Compradas por separado costarían 158 €; en combo, con descuento.",
    price_cents: 11900,
    preview_url: "/demos/concesionaria-premium/index.html",
    gradient: "linear-gradient(160deg,#101522,#1e4fd6 55%,#101522)",
    features: [
      "Incluye el sitio web Concesionaria Plus",
      "Incluye el PDV Concesionaria Pro",
      "Ahorra frente a la compra por separado",
      "Ideal para concesionarias y talleres mecánicos",
      "Dos archivos de descarga, uno por cada parte",
    ],
    tags: [
      "combo", "concesionaria", "taller-mecanico", "demo:concesionaria-premium", "demo:pdv-concesionaria-pro",
      "incluye:concesionaria-plus", "incluye:pdv-concesionaria-pro",
    ],
    thumbnailSlug: "concesionaria-plus",
  },
];

/** Degradado por slug — respaldo de miniatura en las tarjetas. */
export const templateGradients: Record<string, string> = Object.fromEntries(
  seed.map((t) => [t.slug, t.gradient]),
);

/** Se muestran primero en "Templates Más Populares" mientras no haya ventas reales. */
const FEATURED_SLUGS = [
  "concesionaria-plus", "techstore", "sabor-express", "servicios-pro",
  "greennature-spa", "business-pro", "portfolio-creative", "magazine-pro",
];

export const seedTemplates: TemplateWithCategory[] = seed.map((t) => ({
  id: t.id,
  category_id: byslug(t.categorySlug).id,
  title: t.title,
  slug: t.slug,
  short_description: t.short_description,
  full_description: t.full_description,
  price_cents: t.price_cents,
  compare_at_price_cents: null,
  preview_url: t.preview_url,
  // Maqueta del diseño real, generada por scripts/generate-thumbnails.mjs.
  thumbnail_url: `/thumbnails/${t.thumbnailSlug ?? t.slug}.jpg`,
  features: t.features,
  tags: t.tags ?? [],
  featured: FEATURED_SLUGS.includes(t.slug),
  file_url: null,
  status: "published",
  category: byslug(t.categorySlug),
  images: [],
}));

/**
 * Contenido de ejemplo para las tablas de configuración/CMS: alimenta el
 * sitio cuando Supabase todavía no está configurado, igual que
 * `seedCategories`/`seedTemplates` con el catálogo.
 */
export const seedSiteSettings: SiteSettings = {
  company_name: "Leuname Software",
  logo_url: null,
  favicon_url: null,
  email: "hola@leunamesoftware.com",
  phone: null,
  whatsapp: null,
  address: null,
  currency: "EUR",
  language: "es",
  social: {},
  footer_text: "Plantillas profesionales para impulsar tu negocio en línea.",
};

export const seedHomepageContent: HomepageContent = {
  hero: {
    eyebrow: "Marketplace de plantillas",
    title: "Los mejores templates para tu próximo proyecto",
    subtitle:
      "Plantillas profesionales, modernas y 100% personalizables para impulsar tu negocio en línea.",
    image_url: null,
    button_text: "Explorar templates",
    button_href: "/plantillas",
    search_placeholder: "Buscar templates...",
    trust_badges: ["Descarga inmediata", "Pago seguro", "Actualizaciones gratuitas", "Soporte dedicado"],
  },
  benefits: [
    { icon: "sparkles", title: "Templates Premium", text: "Diseños profesionales listos para usar." },
    { icon: "pencil", title: "Fácil de Personalizar", text: "Edita colores, textos e imágenes sin complicaciones." },
    { icon: "devices", title: "Compatible y Responsivo", text: "Se ven perfectos en cualquier dispositivo." },
    { icon: "refresh", title: "Actualizaciones Constantes", text: "Nuevos diseños cada semana para ti." },
  ],
  featured_categories: [],
  featured_templates: [],
  why_us: {
    title: "¿Por qué elegirnos?",
    text: "Más de 10.000 clientes confían en nosotros para llevar sus proyectos al siguiente nivel.",
    button_text: "Conoce más sobre nosotros",
    button_href: "/contacto",
    stats: [
      { value: "10K+", label: "Clientes satisfechos" },
      { value: "500+", label: "Templates disponibles" },
      { value: "5★", label: "Calificación promedio" },
      { value: "24/7", label: "Soporte dedicado" },
    ],
  },
  newsletter: {
    title: "Suscríbete a nuestro newsletter",
    subtitle: "Recibe novedades, ofertas exclusivas y nuevos templates.",
    button_text: "Suscribirme",
  },
};

export const seedTestimonials: Testimonial[] = [
  {
    id: "t1",
    customer_name: "Carlos M.",
    role: "Emprendedor",
    avatar_url: null,
    comment: "Los templates son increíbles y fáciles de personalizar. Mi sitio web quedó profesional y moderno.",
    rating: 5,
    sort_order: 1,
    is_published: true,
  },
  {
    id: "t2",
    customer_name: "Laura G.",
    role: "Dueña de Tienda Online",
    avatar_url: null,
    comment: "Excelente soporte y calidad en los diseños. Volveré a comprar sin duda.",
    rating: 5,
    sort_order: 2,
    is_published: true,
  },
  {
    id: "t3",
    customer_name: "Javier R.",
    role: "Desarrollador Web",
    avatar_url: null,
    comment: "Me ahorraron mucho tiempo y dinero. 100% recomendados.",
    rating: 5,
    sort_order: 3,
    is_published: true,
  },
];
