-- ============================================================
-- Leuname Software — datos de ejemplo
-- Ejecutar DESPUÉS de 0001_schema_inicial.sql.
--
-- GENERADO por scripts/generate-seed-sql.py desde src/lib/seed-data.ts.
-- No editar a mano: cambia el catálogo en el TypeScript y vuelve a generar.
-- ============================================================

insert into public.categories (id, name, slug, icon) values
  ('11111111-1111-4111-8111-000000000001', 'Clínica Dental', 'clinica-dental', '🦷'),
  ('11111111-1111-4111-8111-000000000002', 'Clínica Veterinaria', 'clinica-veterinaria', '🐾'),
  ('11111111-1111-4111-8111-000000000003', 'Pet Shop', 'pet-shop', '🐕'),
  ('11111111-1111-4111-8111-000000000004', 'Agencia Inmobiliaria', 'inmobiliaria', '🏡'),
  ('11111111-1111-4111-8111-000000000005', 'Agencia de Viajes', 'agencia-viajes', '✈️'),
  ('11111111-1111-4111-8111-000000000006', 'Hotel', 'hotel', '🏨'),
  ('11111111-1111-4111-8111-000000000007', 'Restaurantes', 'restaurante', '🍽️'),
  ('11111111-1111-4111-8111-000000000008', 'Panadería', 'panaderia', '🥖'),
  ('11111111-1111-4111-8111-000000000009', 'Boutique de Moda', 'boutique-moda', '👗'),
  ('11111111-1111-4111-8111-000000000010', 'Muebles y Decoración', 'muebles-decoracion', '🛋️'),
  ('11111111-1111-4111-8111-000000000011', 'Taller Mecánico', 'taller-mecanico', '🔧'),
  ('11111111-1111-4111-8111-000000000012', 'Piezas Automotrices', 'piezas-auto', '⚙️'),
  ('11111111-1111-4111-8111-000000000013', 'Taller de Motos', 'taller-motos', '🏍️'),
  ('11111111-1111-4111-8111-000000000014', 'Piezas para Moto', 'piezas-moto', '🔩'),
  ('11111111-1111-4111-8111-000000000015', 'Pizzería', 'pizzeria', '🍕'),
  ('11111111-1111-4111-8111-000000000016', 'Materiales de Construcción', 'materiales-construccion', '🧱'),
  ('11111111-1111-4111-8111-000000000017', 'Obras y Construcción', 'obras-construccion', '🏗️'),
  ('11111111-1111-4111-8111-000000000018', 'Pesca', 'pesca', '🎣'),
  ('11111111-1111-4111-8111-000000000021', 'Energía Solar', 'energia-solar', '☀️'),
  ('11111111-1111-4111-8111-000000000022', 'Mudanzas y Transportes', 'mudanzas-transportes', '🚚'),
  ('11111111-1111-4111-8111-000000000023', 'Electrónica', 'electronica', '📱'),
  ('11111111-1111-4111-8111-000000000024', 'Hamburguesería', 'hamburgueseria', '🍔'),
  ('11111111-1111-4111-8111-000000000025', 'Alquiler de Coches', 'alquiler-coches', '🚗'),
  ('11111111-1111-4111-8111-000000000026', 'Concesionaria de Automóviles', 'concesionaria', '🚘'),
  ('11111111-1111-4111-8111-000000000027', 'Instrumentos Musicales', 'instrumentos-musicales', '🎸'),
  ('11111111-1111-4111-8111-000000000028', 'Perfumería', 'perfumeria', '🧴'),
  ('11111111-1111-4111-8111-000000000029', 'Relojería', 'relojeria', '⌚'),
  ('11111111-1111-4111-8111-000000000030', 'Frutería y Verdulería', 'fruteria', '🥬'),
  ('11111111-1111-4111-8111-000000000031', 'Abogados y Consultoría Legal', 'abogados', '⚖️'),
  ('11111111-1111-4111-8111-000000000032', 'Negocios', 'negocios', '💼'),
  ('11111111-1111-4111-8111-000000000033', 'Tienda Online', 'tienda-online', '🛒'),
  ('11111111-1111-4111-8111-000000000034', 'Salud y Belleza', 'salud-belleza', '💆'),
  ('11111111-1111-4111-8111-000000000035', 'Portafolios', 'portafolios', '🖼️'),
  ('11111111-1111-4111-8111-000000000036', 'Blogs y Revistas', 'blogs-revistas', '📰'),
  ('11111111-1111-4111-8111-000000000037', 'Servicios Profesionales', 'servicios-profesionales', '🤝')
on conflict (id) do update
  set name = excluded.name,
      slug = excluded.slug,
      icon = excluded.icon;

insert into public.templates
  (id, category_id, title, slug, short_description, full_description, price_cents, preview_url, thumbnail_url, features, status)
values
  ('22222222-2222-4222-8222-000000000001',
   '11111111-1111-4111-8111-000000000001',
   'Clínica Dental Premium', 'clinica-dental-premium',
   'Clínica dental completa: tratamientos, equipo, urgencias y cita previa online.',
   'Para clínicas dentales y consultas privadas: catálogo de 6 tratamientos con ficha propia, equipo de especialistas, franja de urgencias 24h, promoción de bienvenida, preguntas frecuentes y formulario de cita previa. Paleta blanco + azul que transmite confianza, higiene y tecnología.',
   19900, '/demos/clinica-dental-premium/index.html', '/thumbnails/clinica-dental-premium.jpg',
   '["Cita previa online con formulario validado", "6 tratamientos con ficha propia", "Equipo de especialistas", "Urgencias 24h y financiación", "Preguntas frecuentes (acordeón)", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000002',
   '11111111-1111-4111-8111-000000000005',
   'Agencia de Viajes Premium', 'agencia-viajes-premium',
   'Agencia de viajes con buscador, destinos, paquetes y planificación a medida.',
   'Para agencias de viajes y turoperadores: buscador de viajes, carrusel de destinos destacados con precios y valoraciones, tarjetas de cruceros y ofertas, 8 tipos de viaje filtrables, paquetes preparados, testimonios, preguntas frecuentes, blog y formulario de propuesta a medida con validación. Paleta verde azulado + coral, tipografía Playfair Display.',
   21900, '/demos/agencia-viajes-premium/index.html', '/thumbnails/agencia-viajes-premium.jpg',
   '["Buscador de viajes funcional", "Carrusel de destinos con valoraciones", "8 tipos de viaje filtrables", "Paquetes y ofertas destacadas", "Formulario de propuesta con validación", "Preguntas frecuentes y blog", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000003',
   '11111111-1111-4111-8111-000000000031',
   'Consultoría Legal & Empresarial Premium', 'consultoria-legal-premium',
   'Despacho de abogados con 10 áreas de especialización, blog jurídico y formulario de consulta.',
   'Para despachos de abogados y consultoras: las 10 áreas más demandadas del derecho con ficha propia (empresarial, laboral, familia, inmobiliario, civil, penal, fiscal, comercial, propiedad intelectual y consultoría), proceso de trabajo en cuatro pasos, opiniones de clientes, blog jurídico, preguntas frecuentes y formulario de consulta con validación. Paleta azul noche + oro, tipografía Playfair Display. No necesita fotos: la balanza de la portada y los iconos de las áreas están dibujados en vectores, así que se ven nítidos en cualquier pantalla y la web carga al instante.',
   24900, '/demos/consultoria-legal-premium/index.html', '/thumbnails/consultoria-legal-premium.jpg',
   '["10 áreas de especialización con icono propio", "Formulario de consulta con validación", "Proceso de trabajo en cuatro pasos", "Blog jurídico y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000004',
   '11111111-1111-4111-8111-000000000007',
   'Restaurante Premium', 'restaurante-premium',
   'Restaurante de cocina de autor: carta con precios, reservas, galería y blog.',
   'Para restaurantes de cocina de autor y locales con carta de vinos: portada con carrusel de fotos, buscador de disponibilidad, seis secciones con foto propia, carta completa agrupada en entrantes, principales y postres con sus precios, cifras del local, opiniones que van rotando solas, galería, blog y formulario de reserva con validación (email, teléfono y fechas pasadas). Paleta negro + terracota + oro, tipografía Playfair Display. El dueño cambia la carta entera desde el panel escribiendo una línea por plato.',
   24900, '/demos/restaurante-premium/index.html', '/thumbnails/restaurante-premium.jpg',
   '["Carta completa con precios, editable línea a línea", "Portada con carrusel de hasta 4 fotos", "Buscador de disponibilidad y formulario de reserva", "Galería de 8 fotos y blog", "Opiniones de clientes que rotan solas", "Botón de WhatsApp para reservas", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000005',
   '11111111-1111-4111-8111-000000000008',
   'Panadería con Pedidos Online', 'panaderia-premium',
   'Panadería con catálogo de productos, cesta y pedidos que llegan por WhatsApp.',
   'Para panaderías, pastelerías y cafeterías que quieren vender sin depender de las plataformas de reparto: catálogo de productos por categorías con filtros, cesta de la compra que recuerda lo que has elegido aunque cierres la página, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio, con productos, cantidades, totales, dirección y hora. Sin comisiones por pedido y sin pasarela de pago que configurar. Paleta crema + ámbar, tipografía Playfair Display.',
   19900, '/demos/panaderia-premium/index.html', '/thumbnails/panaderia-premium.jpg',
   '["Catálogo de productos con filtros por categoría", "Cesta de la compra que no se pierde al cerrar", "Recogida en tienda o entrega, con pedido mínimo", "El pedido llega entero por WhatsApp", "Sin comisiones y sin pasarela que configurar", "Horarios, historia del negocio y contacto", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000006',
   '11111111-1111-4111-8111-000000000002',
   'Clínica Veterinaria Premium', 'veterinaria-premium',
   'Clínica veterinaria con urgencias 24h, planes de salud mensuales y cita online.',
   'Para clínicas veterinarias y centros de salud animal: ocho servicios con ficha propia, franja de urgencias 24 horas con llamada directa, tres planes de salud por cuota mensual (cachorro, adulto y sénior) con el plan destacado resaltado en color, equipo con su especialidad, formulario de cita que pregunta qué animal es y valida teléfono, correo y fechas pasadas, opiniones y preguntas frecuentes. Paleta verde + melocotón, tipografía Playfair Display. No necesita fotos: la portada dibuja un perro y un gato ilustrados, los servicios llevan iconos y el equipo se muestra con sus iniciales, así que se ve nítido en cualquier pantalla y carga al instante.',
   22900, '/demos/veterinaria-premium/index.html', '/thumbnails/veterinaria-premium.jpg',
   '["Tres planes de salud por cuota mensual", "Franja de urgencias 24h con llamada directa", "8 servicios con icono propio", "Cita online que pregunta qué animal es", "Sin fotos: todo ilustrado, carga al instante", "Equipo, opiniones y preguntas frecuentes", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000007',
   '11111111-1111-4111-8111-000000000003',
   'Pet Shop Premium', 'pet-shop-premium',
   'Tienda de mascotas con catálogo, carrito, favoritos y servicios de peluquería y hotel.',
   'Para tiendas de animales y centros de estética canina: catálogo de productos con etiquetas de oferta y novedad, valoraciones con estrellas, carrito de la compra con favoritos que recuerda lo elegido, ocho categorías filtrables (perros, gatos, pequeños animales...), franja de servicios (baño y peluquería, hotel, guardería, adiestramiento) y pedido que se envía por WhatsApp. Paleta azul petróleo + terracota, tipografía Inter.',
   21900, '/demos/pet-shop-premium/index.html', '/thumbnails/pet-shop-premium.jpg',
   '["Catálogo con ofertas, novedades y valoraciones", "Carrito de la compra con favoritos", "8 categorías filtrables", "Servicios de peluquería, hotel y guardería", "El pedido llega por WhatsApp", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000008',
   '11111111-1111-4111-8111-000000000030',
   'Frutería y Verdulería Premium', 'fruteria-premium',
   'Frutería online con catálogo de productos frescos, ofertas y carrito de compra.',
   'Para fruterías, verdulerías y tiendas de productos ecológicos: catálogo con ofertas y novedades, ocho categorías filtrables (frutas, verduras, frutos secos, ecológicos...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta verde + terracota, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios, así que carga al instante.',
   19900, '/demos/fruteria-premium/index.html', '/thumbnails/fruteria-premium.jpg',
   '["Catálogo con ofertas y novedades", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000009',
   '11111111-1111-4111-8111-000000000029',
   'Relojería Premium', 'relojeria-premium',
   'Relojería online con catálogo de marcas, valoraciones y carrito de compra.',
   'Para relojerías y joyerías: catálogo de relojes con etiquetas de oferta y novedad, valoraciones con estrellas, ocho categorías filtrables (hombre, mujer, smartwatch, joyería...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul noche + dorado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/relojeria-premium/index.html', '/thumbnails/relojeria-premium.jpg',
   '["Catálogo con ofertas, novedades y valoraciones", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000010',
   '11111111-1111-4111-8111-000000000012',
   'Piezas Automotrices Premium', 'piezas-auto-premium',
   'Tienda de piezas de automóvil con catálogo, ofertas y carrito de compra.',
   'Para tiendas de recambios y piezas de automóvil: catálogo con descuentos destacados, ocho categorías filtrables (frenos, motor, suspensión, electricidad...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta roja + gris oscuro, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/piezas-auto-premium/index.html', '/thumbnails/piezas-auto-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000011',
   '11111111-1111-4111-8111-000000000014',
   'Piezas para Moto Premium', 'piezas-moto-premium',
   'Tienda de recambios de moto con catálogo, ofertas y carrito de compra.',
   'Para tiendas de recambios de motocicleta: catálogo con descuentos destacados, ocho categorías filtrables (frenos, motor, escapes, equipación...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta roja + gris oscuro, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   19900, '/demos/piezas-moto-premium/index.html', '/thumbnails/piezas-moto-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000012',
   '11111111-1111-4111-8111-000000000010',
   'Muebles y Decoración Premium', 'muebles-decoracion-premium',
   'Tienda de muebles y decoración con catálogo, ofertas y carrito de compra.',
   'Para tiendas de muebles y decoración del hogar: catálogo con descuentos destacados, ocho categorías filtrables (salón, dormitorio, iluminación, textiles...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta terracota + crema, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/muebles-decoracion-premium/index.html', '/thumbnails/muebles-decoracion-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000013',
   '11111111-1111-4111-8111-000000000028',
   'Perfumería Premium', 'perfumeria-premium',
   'Perfumería online con catálogo de fragancias, ofertas y carrito de compra.',
   'Para perfumerías y tiendas de cosmética: catálogo con descuentos destacados, ocho categorías filtrables (mujer, hombre, unisex, cosmética...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta morada + rosa, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   19900, '/demos/perfumeria-premium/index.html', '/thumbnails/perfumeria-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000014',
   '11111111-1111-4111-8111-000000000018',
   'Pesca Premium', 'pesca-premium',
   'Tienda de artículos de pesca con catálogo, ofertas y carrito de compra.',
   'Para tiendas de artículos de pesca: catálogo con descuentos destacados, ocho categorías filtrables (cañas, carretes, señuelos, ropa...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + verde, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   19900, '/demos/pesca-premium/index.html', '/thumbnails/pesca-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000015',
   '11111111-1111-4111-8111-000000000021',
   'Energía Solar Premium', 'energia-solar-premium',
   'Tienda de energía solar con catálogo de productos y solicitud de presupuesto.',
   'Para instaladoras y tiendas de energía solar: catálogo de placas, inversores, baterías y kits solares, ocho categorías filtrables, carrito de la compra con favoritos y pedido o solicitud de presupuesto que se envía por WhatsApp. Paleta azul noche + amarillo solar, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   22900, '/demos/energia-solar-premium/index.html', '/thumbnails/energia-solar-premium.jpg',
   '["Catálogo con 8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido o presupuesto llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Pensado para instaladoras y tiendas técnicas", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000016',
   '11111111-1111-4111-8111-000000000011',
   'Taller Mecánico Premium', 'taller-mecanico-premium',
   'Taller mecánico con cita online, 10 servicios y formulario de presupuesto.',
   'Para talleres mecánicos y centros de diagnóstico: diez áreas de servicio con ficha propia (diagnóstico electrónico, frenos, neumáticos, ITV...), proceso de trabajo en cuatro pasos, cifras del taller, opiniones de clientes, blog y formulario de cita con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   22900, '/demos/taller-mecanico-premium/index.html', '/thumbnails/taller-mecanico-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de cita con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000017',
   '11111111-1111-4111-8111-000000000013',
   'Taller de Motos Premium', 'taller-motos-premium',
   'Taller de motos con cita online, 10 servicios y formulario de presupuesto.',
   'Para talleres especializados en motocicletas: diez áreas de servicio con ficha propia (mantenimiento, neumáticos, cadena, restauración...), proceso de trabajo en cuatro pasos, cifras del taller, opiniones de clientes, blog y formulario de cita con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   22900, '/demos/taller-motos-premium/index.html', '/thumbnails/taller-motos-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de cita con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000018',
   '11111111-1111-4111-8111-000000000022',
   'Mudanzas y Transportes Premium', 'mudanzas-transportes-premium',
   'Empresa de mudanzas con 10 servicios y formulario de solicitud de presupuesto.',
   'Para empresas de mudanzas y transporte: diez áreas de servicio con ficha propia (mudanzas particulares, internacionales, guarda-muebles...), proceso de trabajo en cuatro pasos, cifras de la empresa, opiniones de clientes, blog y formulario de presupuesto con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   22900, '/demos/mudanzas-transportes-premium/index.html', '/thumbnails/mudanzas-transportes-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de presupuesto con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000019',
   '11111111-1111-4111-8111-000000000017',
   'Obras y Construcción Premium', 'obras-construccion-premium',
   'Empresa de construcción con 10 servicios y formulario de solicitud de presupuesto.',
   'Para empresas de obras y construcción: diez áreas de servicio con ficha propia (reformas integrales, obra nueva, rehabilitación...), proceso de trabajo en cuatro pasos, cifras de la empresa, opiniones de clientes, blog y formulario de presupuesto con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   24900, '/demos/obras-construccion-premium/index.html', '/thumbnails/obras-construccion-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de presupuesto con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000020',
   '11111111-1111-4111-8111-000000000015',
   'Pizzería Premium', 'pizzeria-premium',
   'Pizzería con pedidos online, cesta de la compra y entrega o recogida en tienda.',
   'Para pizzerías y restaurantes italianos que quieren vender sin depender de las plataformas de reparto: catálogo de pizzas por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + rojo italiano, tipografía Playfair Display.',
   19900, '/demos/pizzeria-premium/index.html', '/thumbnails/pizzeria-premium.jpg',
   '["Catálogo de pizzas con filtros por categoría", "Cesta de la compra que no se pierde al cerrar", "Recogida en tienda o entrega, con pedido mínimo", "El pedido llega entero por WhatsApp", "Sin comisiones y sin pasarela que configurar", "Horarios, historia del negocio y contacto", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000021',
   '11111111-1111-4111-8111-000000000009',
   'Boutique de Moda Premium', 'boutique-moda-premium',
   'Boutique de moda online con catálogo, ofertas y carrito de compra.',
   'Para boutiques de moda y tiendas de ropa: catálogo con descuentos destacados, ocho categorías filtrables (mujer, hombre, calzado, accesorios...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta rosa + terracota, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   19900, '/demos/boutique-moda-premium/index.html', '/thumbnails/boutique-moda-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000022',
   '11111111-1111-4111-8111-000000000023',
   'Electrónica Premium', 'electronica-premium',
   'Tienda de electrónica con catálogo, ofertas y carrito de compra.',
   'Para tiendas de electrónica y tecnología: catálogo con descuentos destacados, ocho categorías filtrables (móviles, portátiles, audio, gaming...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + morado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/electronica-premium/index.html', '/thumbnails/electronica-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000023',
   '11111111-1111-4111-8111-000000000016',
   'Materiales de Construcción Premium', 'materiales-construccion-premium',
   'Almacén de materiales de construcción con catálogo y carrito de compra.',
   'Para almacenes de materiales de construcción y ferreterías: catálogo con ocho categorías filtrables (cemento, ladrillos, herramientas, maquinaria...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta terracota + amarillo, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/materiales-construccion-premium/index.html', '/thumbnails/materiales-construccion-premium.jpg',
   '["Catálogo con 8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Pensado para almacenes y ferreterías", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000024',
   '11111111-1111-4111-8111-000000000024',
   'Hamburguesería Premium', 'hamburgueseria-premium',
   'Hamburguesería con pedidos online, cesta de la compra y entrega o recogida en tienda.',
   'Para hamburgueserías y locales de comida rápida de calidad: catálogo de hamburguesas por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + terracota, tipografía Playfair Display.',
   19900, '/demos/hamburgueseria-premium/index.html', '/thumbnails/hamburgueseria-premium.jpg',
   '["Catálogo de hamburguesas con filtros por categoría", "Cesta de la compra que no se pierde al cerrar", "Recogida en tienda o entrega, con pedido mínimo", "El pedido llega entero por WhatsApp", "Sin comisiones y sin pasarela que configurar", "Horarios, historia del negocio y contacto", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000025',
   '11111111-1111-4111-8111-000000000004',
   'Agencia Inmobiliaria Premium', 'inmobiliaria-premium',
   'Inmobiliaria con 10 servicios, valoración gratuita y formulario de contacto.',
   'Para agencias inmobiliarias: diez áreas de servicio con ficha propia (venta, alquiler, obra nueva, valoración, asesoría hipotecaria...), proceso de trabajo en cuatro pasos, cifras de la agencia, opiniones de clientes, blog y formulario de contacto con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   22900, '/demos/inmobiliaria-premium/index.html', '/thumbnails/inmobiliaria-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de contacto con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000026',
   '11111111-1111-4111-8111-000000000006',
   'Hotel Premium', 'hotel-premium',
   'Hotel con 10 servicios, reserva directa y formulario de contacto.',
   'Para hoteles y alojamientos: diez áreas de servicio con ficha propia (habitaciones, suites, restaurante, spa, eventos...), proceso de reserva en cuatro pasos, cifras del hotel, opiniones de huéspedes, blog y formulario de reserva con validación. Paleta azul noche + dorado, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   22900, '/demos/hotel-premium/index.html', '/thumbnails/hotel-premium.jpg',
   '["10 áreas de servicio con icono propio", "Formulario de reserva con validación", "Proceso de reserva en cuatro pasos", "Blog y preguntas frecuentes", "Botones de WhatsApp, teléfono y email", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000027',
   '11111111-1111-4111-8111-000000000025',
   'Alquiler de Coches Premium', 'alquiler-coches-premium',
   'Alquiler de coches con flota propia, catálogo por categorías y reserva por WhatsApp.',
   'Para empresas de alquiler de coches con flota propia: catálogo de vehículos por categorías (económicos, SUV, eléctricos, lujo...), carrito de reserva con favoritos y solicitud que se envía por WhatsApp. Paleta negro + amarillo, tipografía Inter. No necesita fotos de vehículo: todo se muestra con iconos propios.',
   22900, '/demos/alquiler-coches-premium/index.html', '/thumbnails/alquiler-coches-premium.jpg',
   '["Catálogo de vehículos por categorías", "Carrito de reserva con favoritos", "La solicitud llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Pensado para empresas con flota propia", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000028',
   '11111111-1111-4111-8111-000000000026',
   'Concesionaria de Automóviles Premium', 'concesionaria-premium',
   'Concesionaria con vehículos nuevos y de ocasión, catálogo y solicitud por WhatsApp.',
   'Para concesionarias de automóviles: catálogo de vehículos nuevos y de ocasión por categorías, carrito de interés con favoritos y solicitud de información que se envía por WhatsApp. Paleta negro + amarillo, tipografía Inter. No necesita fotos de vehículo: todo se muestra con iconos propios.',
   22900, '/demos/concesionaria-premium/index.html', '/thumbnails/concesionaria-premium.jpg',
   '["Catálogo de nuevos y de ocasión por categorías", "Carrito de interés con favoritos", "La solicitud llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Pensado para concesionarias con vehículos propios", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000029',
   '11111111-1111-4111-8111-000000000027',
   'Tienda de Instrumentos Musicales Premium', 'instrumentos-musicales-premium',
   'Tienda de instrumentos musicales con catálogo, ofertas y carrito de compra.',
   'Para tiendas de instrumentos musicales y equipos de sonido: catálogo con descuentos destacados, ocho categorías filtrables (guitarras, baterías, teclados, micrófonos...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta negro + dorado, tipografía Inter. No necesita fotos de producto: todo se muestra con iconos propios.',
   21900, '/demos/instrumentos-musicales-premium/index.html', '/thumbnails/instrumentos-musicales-premium.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Sin fotos: todo ilustrado, carga al instante", "Newsletter y franja de confianza", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000030',
   '11111111-1111-4111-8111-000000000032',
   'Concesionaria Plus', 'concesionaria-plus',
   'Concesionaria de coches con catálogo, financiación y solicitud por WhatsApp.',
   'Para concesionarias y comercializadoras de vehículos: catálogo de coches nuevos y de ocasión con buscador por categoría, marca, año y precio, franjas de financiación y seguro, tasación de vehículo y solicitud de información directa por WhatsApp. Paleta roja + negra, tipografía Inter.',
   5900, '/demos/concesionaria-premium/index.html', '/thumbnails/concesionaria-plus.jpg',
   '["Buscador de vehículos por categoría, marca y año", "Financiación, seguro y tasación", "Solicitud de información por WhatsApp", "Favoritos (''Mi garaje'')", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000031',
   '11111111-1111-4111-8111-000000000033',
   'TechStore', 'techstore',
   'Tienda online de electrónica con catálogo, carrito y pedido por WhatsApp.',
   'Para tiendas de electrónica y tecnología: catálogo de productos con descuentos destacados, ocho categorías filtrables (móviles, portátiles, audio, gaming...), carrito de la compra con favoritos y pedido que se envía por WhatsApp. Paleta azul + morado, tipografía Inter.',
   6900, '/demos/electronica-premium/index.html', '/thumbnails/techstore.jpg',
   '["Catálogo con descuentos destacados", "8 categorías filtrables", "Carrito de la compra con favoritos", "El pedido llega por WhatsApp", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000032',
   '11111111-1111-4111-8111-000000000007',
   'Sabor Express', 'sabor-express',
   'Comida rápida con pedidos online, cesta de la compra y entrega o recogida en tienda.',
   'Para hamburgueserías y locales de comida rápida de calidad: catálogo por categorías con filtros, cesta de la compra que recuerda lo elegido, elección entre recoger en tienda o entrega a domicilio con su coste y su pedido mínimo, y un formulario que arma el pedido completo y lo manda al WhatsApp del negocio. Sin comisiones por pedido. Paleta negro + terracota, tipografía Playfair Display.',
   4900, '/demos/hamburgueseria-premium/index.html', '/thumbnails/sabor-express.jpg',
   '["Catálogo con filtros por categoría", "Cesta de la compra que no se pierde al cerrar", "Recogida en tienda o entrega, con pedido mínimo", "El pedido llega entero por WhatsApp", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published'),

  ('22222222-2222-4222-8222-000000000033',
   '11111111-1111-4111-8111-000000000037',
   'Servicios Pro', 'servicios-pro',
   'Consultoría profesional con áreas de especialización, blog y formulario de consulta.',
   'Para despachos y consultoras de servicios profesionales: áreas de especialización con ficha propia, proceso de trabajo en cuatro pasos, opiniones de clientes, blog y formulario de consulta con validación. Paleta azul noche + oro, tipografía Playfair Display. No necesita fotos: todo en vectores, carga al instante.',
   6900, '/demos/consultoria-legal-premium/index.html', '/thumbnails/servicios-pro.jpg',
   '["Áreas de especialización con icono propio", "Formulario de consulta con validación", "Proceso de trabajo en cuatro pasos", "Blog y preguntas frecuentes", "Sin fotos: todo en vectores, carga al instante", "Responsive (móvil, tablet y desktop)", "Optimizado para Google (SEO)"]'::jsonb,
   'published')

on conflict (id) do update
  set title             = excluded.title,
      slug              = excluded.slug,
      category_id       = excluded.category_id,
      short_description = excluded.short_description,
      full_description  = excluded.full_description,
      price_cents       = excluded.price_cents,
      preview_url       = excluded.preview_url,
      thumbnail_url     = excluded.thumbnail_url,
      features          = excluded.features,
      status            = excluded.status;
